-- MySQL Script generated by MySQL Workbench
-- Tue Aug 18 14:40:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ITS_KENNEDY
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ITS_KENNEDY` ;

-- -----------------------------------------------------
-- Schema ITS_KENNEDY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ITS_KENNEDY` DEFAULT CHARACTER SET utf8 ;
USE `ITS_KENNEDY` ;

-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`HW`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`HW` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`HW` (
  `idHW` INT NOT NULL AUTO_INCREMENT,
  `Cpu` VARCHAR(45) NULL DEFAULT NULL,
  `Ram` INT NULL DEFAULT NULL,
  `Memoria` INT NULL DEFAULT NULL,
  `Tipo_memoria` TINYINT NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `modello` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idHW`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`SEDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`SEDE` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`SEDE` (
  `idSEDE` INT NOT NULL,
  `SEDE` VARCHAR(100) NULL,
  PRIMARY KEY (`idSEDE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`PC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`PC` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`PC` (
  `idpc` INT NOT NULL AUTO_INCREMENT,
  `HW_idHW` INT NOT NULL,
  `Seriale` VARCHAR(70) NOT NULL,
  `n_inventario` VARCHAR(45) NOT NULL,
  `n_fattura` VARCHAR(45) NOT NULL,
  `data_Acquisto` DATE NOT NULL,
  `guasto` TINYINT NULL DEFAULT NULL,
  `note` VARCHAR(500) NULL DEFAULT NULL,
  `K_O` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`idpc`),
  INDEX `fk_PC_HW_idx` (`HW_idHW` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`UTENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`UTENTE` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`UTENTE` (
  `idUTENTE` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(70) NULL DEFAULT NULL,
  `cognome` VARCHAR(70) NULL DEFAULT NULL,
  `data_nascita` DATE NULL DEFAULT NULL,
  `luogo_nascita` VARCHAR(70) NULL DEFAULT NULL,
  `via` VARCHAR(70) NULL DEFAULT NULL,
  `civico` INT NULL DEFAULT NULL,
  `comune` VARCHAR(100) NULL DEFAULT NULL,
  `provincia_sigla` VARCHAR(4) NULL DEFAULT NULL,
  `tipo_utente` VARCHAR(50) NULL DEFAULT NULL,
  `corso` VARCHAR(100) NULL DEFAULT NULL,
  `frequentazione` TINYINT NULL DEFAULT NULL,
  `SEDE_idSEDE` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`idUTENTE`),
  INDEX `fk_UTENTE_SEDE1_idx` (`SEDE_idSEDE` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`MOVIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`MOVIMENTO` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`MOVIMENTO` (
  `idMOVIMENTO` INT NOT NULL AUTO_INCREMENT,
  `data_consegna` VARCHAR(45) NULL DEFAULT NULL,
  `cavo_rete` TINYINT NULL DEFAULT NULL,
  `alimentatore` TINYINT NULL DEFAULT NULL,
  `borsa` TINYINT NULL DEFAULT NULL,
  `mouse` TINYINT NULL DEFAULT NULL,
  `hdd` TINYINT NULL DEFAULT NULL,
  `con_ethernet` TINYINT NULL DEFAULT NULL,
  `con_usb` TINYINT NULL DEFAULT NULL,
  `note` VARCHAR(500) NULL DEFAULT NULL,
  `motivo_movimento` VARCHAR(200) NULL DEFAULT NULL,
  `PC_idpc` INT NOT NULL,
  `UTENTE_idUTENTE` INT NOT NULL,
  `entrata` TINYINT NULL DEFAULT NULL,
  `uscita` TINYINT NULL DEFAULT NULL,
  `guasto` TINYINT NULL DEFAULT NULL,
  `riparazione` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`idMOVIMENTO`),
  INDEX `fk_MOVIMENTO_PC1_idx` (`PC_idpc` ASC) VISIBLE,
  INDEX `fk_MOVIMENTO_UTENTE1_idx` (`UTENTE_idUTENTE` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`GUASTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`GUASTO` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`GUASTO` (
  `idGUASTO` INT NOT NULL AUTO_INCREMENT,
  `data_consegna` DATE NULL DEFAULT NULL,
  `note` VARCHAR(500) NULL DEFAULT NULL,
  `MOVIMENTO_idMOVIMENTO` INT NOT NULL,
  PRIMARY KEY (`idGUASTO`),
  INDEX `fk_GUASTO_MOVIMENTO1_idx` (`MOVIMENTO_idMOVIMENTO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`ADMIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`ADMIN` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`ADMIN` (
  `idADMIN` INT NOT NULL AUTO_INCREMENT,
  `Nome_Admin` VARCHAR(50) NOT NULL,
  `Cognome_Admin` VARCHAR(50) NOT NULL,
  `Username` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  `Password` VARCHAR(300) NOT NULL,
  `RUOLO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idADMIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`ADMIN_has_SEDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`ADMIN_has_SEDE` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`ADMIN_has_SEDE` (
  `ADMIN_idADMIN` INT NOT NULL,
  `SEDE_idSEDE` INT NOT NULL,
  PRIMARY KEY (`ADMIN_idADMIN`, `SEDE_idSEDE`),
  INDEX `fk_ADMIN_has_SEDE_SEDE1_idx` (`SEDE_idSEDE` ASC) VISIBLE,
  INDEX `fk_ADMIN_has_SEDE_ADMIN1_idx` (`ADMIN_idADMIN` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITS_KENNEDY`.`PC_has_SEDE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITS_KENNEDY`.`PC_has_SEDE` ;

CREATE TABLE IF NOT EXISTS `ITS_KENNEDY`.`PC_has_SEDE` (
  `PC_idpc` INT NOT NULL,
  `SEDE_idSEDE` INT NOT NULL,
  PRIMARY KEY (`PC_idpc`, `SEDE_idSEDE`),
  INDEX `fk_PC_has_SEDE_SEDE1_idx` (`SEDE_idSEDE` ASC) VISIBLE,
  INDEX `fk_PC_has_SEDE_PC1_idx` (`PC_idpc` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
